# default values for all particles
[defaults]
    spread = 0
    # we make it white so that i
    color = "#FFFFFF"
    sink_chance = 0
    burn_chance = 0
    update_limit = 120
    game_speed = 1.0

# particle settings 
[[particle]] 
name = "Air"

        #########################################
        color = "#000000" 
        #########################################
[[particle]]
name = "Water"

        #########################################
        type = "liquid"
        spread = 4
        color = ["#0073bd", "#0073CE", "#0073DC"]
        opacity = 0.5
        burn_chance = 0
        #########################################

[[particle]]
name = "Sand"

        #########################################
        type = "solid"
        spread = 1
        sink_chance = 10
        #########################################

[[particle]]
name = "Wood"

        #########################################
        type = "solid"
        color = ["#785602","#996402", "#B4812B"]
        #########################################

[[particle]]
name = "Stone"

        #########################################
        type = "solid"
        color = ["#646464", "#6E6E6E", "#787878"]
        #########################################

[[particle]]
name = "Fire"

        #########################################
        type = "plasma"
        color = ["#E13200", "#FF6400", "#FF9600"]
        #########################################

[[particle]]
name = "FireAura"

        #########################################
        type = "plasma"
        color = ["#701900", "#E33200", "#E34B00"]
        opacity = 0.5
        #########################################
[[particle]] 
name = "Smoke"

        #########################################
        type = "gas"
        color = ["#232323", "#2D2D2D", "#373737"]
        opacity = 0.5
        #########################################
[[particle]] 
name = "Steam"

        #########################################
        type = "gas"
        color = ["#F0F0F0", "#E6E6E6", "#DCDCDC"]
        #########################################

[[particle]]
name = "Snow"

        #########################################
        type = "solid"
        color = ["#FFFFFF", "#F5F5F5", "#F0F0F0"]
        #########################################

[[particle]]
name = "Acid"

        #########################################
        type = "liquid"
        color = ["#009B00", "#009600", "#00A000"]
        #########################################

[[particle]]
name = "ToxicGas"

        #########################################
        type = "gas"
        color = ["#009B00", "#009600", "#00A000"]
        opacity = 0.5
        #########################################
        #[[particle.behaviour]]
        #        [[particle.behaviour.

[[particle]]
name = "Steel"

        #########################################
        type = "solid"
        color = ["#009B00", "#009600", "#00A000"]
        #########################################
        







